import Footer from '@/components/footer/Footer'
import Navbar from '@/components/navBar/Navbar'
import { Inter, Montserrat } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/context/ThemeContex'

const inter = Inter({ subsets: ['latin'] }) //Can create font family like this
const montserrat = Montserrat({ subsets: ['latin'] }) //Can create font family like this

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <div className='container'>
            <Navbar />
            {children}
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
